on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: make build

      - name: Deploy to PyPI
        uses: pypa/gh-action-pypi-publish@v2
        with:
          username: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
